spring:
  application:
    name: wikipedia-to-kafka-service
  profiles:
    active: wikipedia-to-kafka
  config:
    import: configserver:http://config-server:8888
  cloud:
    config:
      name: wikipedia-to-kafka-service, config-client
      uri: http://config-server:8888
    fail-fast: true
    retry:
       initial-interval: 2500
       multiplier: 1.5
       max-attempts: 1000
       max-interval: 30000