spring:
  application:
    name: solr-query-web-client-service
  profiles:
    active: solr-query-web-client-service
  config:
#    import: configserver:http://config-server:8888/
    import: configserver:http://localhost:8888/
  cloud:
    config:
      enabled: true
      allowOverride: true
      overrideNone: true
      name: solr-query-web-client-service,config-client,default-retry-config
      profile: solr-query-web-client-service,config-client,default-retry-config
#      uri: http://config-server:8888
      uri: http://localhost:8888/
# Sample query to config server: http://localhost:8888/solr-server-config,solr-query-service,config-client,default-retry-config/solr-server-config,solr-query-service,config-client,default-retry-config