services:
  kafka-to-solr-service:
    image: wams/kafka-to-solr-service:${SERVICE_VERSION:-latest}
    hostname: kafka-to-solr-service
    user: root
    entrypoint: ["check-config-server-started.sh"]
    ports:
      - "5008:5005"
      - "5109:8080"
    volumes:
      - "../docker-logs:/workspaces/kafka-to-solr-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx4096m"
      - "KAFKA-CONFIG.WIKIPEDIA_TOPIC-NAME=wikipedia.topic"
      - "KAFKA-CONFIG.WIKIPEDIA_BOOTSTRAP-SERVERS=kafka1:19092, kafka2:19093, kafka3:19094"
      - "KAFKA-CONFIG.WIKIPEDIA_SCHEMA-REGISTRY-URL=http://kafka-schema-registry:8081"
      - "SPRING.CONFIG.IMPORT=configserver:http://config-server:8888"
    networks: 
      - wams

networks:
  wams:
    external: true
