services:
  solr-query-web-client-service:
    hostname: solr-query-web-client-service
    image: wams/solr-query-web-client-service:${SERVICE_VERSION:-latest}
    user: root
    ports:
      - "6006:5006"
      - "8184:8184"
      #  external:internal
    volumes:
      - "../docker-logs:/workspaces/solr-query-service/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx1024m"
    networks: 
      - wams

  
networks:
 wams:
   external: true